name: distributed-telemetry-engine

services:

  nginx-proxy:
      image: nginx:alpine
      ports:
        - "${NGINX_PORT:-80}:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - processor-service

  # ─── MICROSERVICES ───
  generator-service:
    build: 
      context: ./telemetry-generator-service
    deploy:
      replicas: ${GENERATOR_REPLICAS:-1}     
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EVENTS_PER_TICK=${GENERATOR_RATE:-50} # 1 second = 10 ticks
      - ANOMALY_RATE=${ANOMALY_RATE:-50} # Per Thousand
    depends_on:
      kafka:
        condition: service_healthy

  processor-service:
    build: 
      context: ./telemetry-processor-service
    deploy:
      replicas: ${PROCESSOR_REPLICAS:-1} 
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started

  # ─── INFRASTRUCTURE ───
  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"  # Exposes the EXTERNAL listener to your host machine
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_OFFER_MAX_REPLICAS_PER_BROKER=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      
      # ─── AUTO-CREATE TOPICS & PARTITIONS ───
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=10
    healthcheck:
      # Updated healthcheck to use the correct internal port
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server 127.0.0.1:29092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=telemetry_db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
